#!/bin/sh /etc/rc.common

START=95
STOP=10
USE_PROCD=1

PROG=/usr/bin/ucode
POLLER=/usr/lib/home-gateway/telegram-poller.uc
GATEWAY=/usr/bin/gateway

start_service() {
	[ -x "$PROG" ] || return 1
	[ -r "$POLLER" ] || return 1
	[ -x "$GATEWAY" ] || return 1

	procd_open_instance
	procd_set_param command "$PROG" "$POLLER" "$GATEWAY" loop
	procd_set_param respawn 3600 5 5
	procd_set_param stderr 1
	procd_close_instance
}
